#!/bin/bash
TARGET_FOLDER=../review_content/steady_state_stack
bash ../source_file_group.sh project_root_cmake_installer ./cmake-3.26.0-linux-x86_64.sh $TARGET_FOLDER
bash ../source_file_group.sh project_root_scripts ./install_promethus.sh,./install_grafana.sh,./install_victoria_metrics.sh,./build_aeronmd.sh,./pre-publish.sh $TARGET_FOLDER
bash ../source_file_group.sh project_root_project_docs_1 ./promotion-plan.md,./README.md,./encrypt-plan.md $TARGET_FOLDER
bash ../source_file_group.sh project_root_project_docs_2 ./intro_doc.md,./values.md,./distributed.md,./talk_intro.md $TARGET_FOLDER
bash ../source_file_group.sh project_root_steady_image ./steady.jpg $TARGET_FOLDER
bash ../source_file_group.sh project_root_steady_happy_image ./steady-happy.jpg $TARGET_FOLDER
bash ../source_file_group.sh project_root_steady_watermark_image ./steady-watermark.jpg $TARGET_FOLDER
bash ../source_file_group.sh project_root_twitter_image ./watch_on_twitter.jpg $TARGET_FOLDER
bash ../source_file_group.sh project_root_cargo_lock ./Cargo.lock $TARGET_FOLDER
bash ../source_file_group.sh project_root_small_files ./cargo_build_release.txt,./cargo_build.txt,./cargo_audit.txt,./cargo_outdated.txt,./cargo_tokei.txt,./cargo_test.txt,./cargo_bloat.txt,./Cargo.toml,./example-app-dirs.txt,./tarpaulin-report.html,./channels.txt,./build_ignore_contex.sh $TARGET_FOLDER
bash ../source_file_group.sh core_shared_overload_image ./core/overload.png $TARGET_FOLDER
bash ../source_file_group.sh core_shared_overload2_image ./core/overload2.png $TARGET_FOLDER
bash ../source_file_group.sh core_shared_simple_example_gif ./core/simple-example.gif $TARGET_FOLDER
bash ../source_file_group.sh core_shared_core_cargo_lock ./core/Cargo.lock $TARGET_FOLDER
bash ../source_file_group.sh core_shared_core_docs_and_build ./core/README.md,./core/build_for_pi.sh,./core/build.rs $TARGET_FOLDER
bash ../source_file_group.sh core_shared_core_graphs ./core/graph_distributed.dot,./core/graph_ros.dot $TARGET_FOLDER
bash ../source_file_group.sh core_shared_core_templates ./core/templates/index.html.txt,./core/templates/webworker.js.txt $TARGET_FOLDER
bash ../source_file_group.sh core_shared_core_small_files ./core/Cargo.toml,./core/cargo_rustdoc.txt,./core/test_all_to_file.dat $TARGET_FOLDER
bash ../source_file_group.sh cargo_tool_main_source ./cargo-steady-state/src/main.rs $TARGET_FOLDER
bash ../source_file_group.sh cargo_tool_source_files ./cargo-steady-state/src/args.rs,./cargo-steady-state/src/templates.rs $TARGET_FOLDER
bash ../source_file_group.sh cargo_tool_extract_details_source ./cargo-steady-state/src/extract_details.rs $TARGET_FOLDER
bash ../source_file_group.sh cargo_tool_templates ./cargo-steady-state/templates/file_main.txt,./cargo-steady-state/templates/file_cargo.txt,./cargo-steady-state/templates/file_args.txt,./cargo-steady-state/templates/file_gitignore.txt,./cargo-steady-state/templates/file_actor.txt,./cargo-steady-state/templates/dockerfile.txt $TARGET_FOLDER
bash ../source_file_group.sh cargo_tool_cargo_and_readme ./cargo-steady-state/Cargo.toml,./cargo-steady-state/README.md $TARGET_FOLDER
bash ../source_file_group.sh cargo_tool_gen_example_image ./cargo-steady-state/gen-example.jpg $TARGET_FOLDER
bash ../source_file_group.sh distributed_distributed_stream ./core/src/distributed/distributed_stream.rs $TARGET_FOLDER
bash ../source_file_group.sh distributed_aeron_subscribe ./core/src/distributed/aeron_subscribe.rs,./core/src/distributed/aeron_subscribe_bundle.rs $TARGET_FOLDER
bash ../source_file_group.sh distributed_aeron_publish_bundle ./core/src/distributed/aeron_publish_bundle.rs $TARGET_FOLDER
bash ../source_file_group.sh distributed_aeron_publish ./core/src/distributed/aeron_publish.rs $TARGET_FOLDER
bash ../source_file_group.sh distributed_aeron_channel_builder ./core/src/distributed/aeron_channel_builder.rs $TARGET_FOLDER
bash ../source_file_group.sh distributed_aeron_channel_structs ./core/src/distributed/aeron_channel_structs.rs $TARGET_FOLDER
bash ../source_file_group.sh distributed_distributed_utils ./core/src/distributed/gather_ignore_context.sh,./core/src/distributed/scheduling.rs,./core/src/distributed/polling.rs,./core/src/distributed/distributed_builder.rs $TARGET_FOLDER
bash ../source_file_group.sh telemetry_metrics_server ./core/src/telemetry/metrics_server.rs $TARGET_FOLDER
bash ../source_file_group.sh telemetry_spinner_image ./core/static/telemetry/images/spinner.gif $TARGET_FOLDER
bash ../source_file_group.sh telemetry_metrics_collector ./core/src/telemetry/metrics_collector.rs $TARGET_FOLDER
bash ../source_file_group.sh telemetry_telemetry_setup ./core/src/telemetry/setup.rs $TARGET_FOLDER
bash ../source_file_group.sh telemetry_telemetry_graphs ./core/static/telemetry/graph.dot,./core/static/telemetry/graph2.dot $TARGET_FOLDER
bash ../source_file_group.sh telemetry_telemetry_web ./core/static/telemetry/dot-viewer.js,./core/static/telemetry/dot-viewer.css,./core/static/telemetry/index.html,./core/static/telemetry/webworker.js,./core/static/telemetry/server.js,./core/static/telemetry/package.json,./core/static/telemetry/README.md $TARGET_FOLDER
bash ../source_file_group.sh telemetry_telemetry_images ./core/static/telemetry/images/user-icon.svg,./core/static/telemetry/images/refresh-time-icon.svg,./core/static/telemetry/images/zoom-in-icon.svg,./core/static/telemetry/images/zoom-out-icon.svg,./core/static/telemetry/images/preview-icon.svg,./core/static/telemetry/images/zoom-out-icon-disabled.svg,./core/static/telemetry/images/zoom-in-icon-disabled.svg,./core/static/telemetry/images/old/speed.png,./core/static/telemetry/images/old/download.png $TARGET_FOLDER
bash ../source_file_group.sh serialize_and_install_serialize ./core/src/serialize/fast_protocol_packed.rs,./core/src/serialize/byte_buffer_packer.rs $TARGET_FOLDER
bash ../source_file_group.sh serialize_and_install_install ./core/src/install/local_cli.rs,./core/src/install/serviced.rs $TARGET_FOLDER
bash ../source_file_group.sh routing_services_mqtt_install ./core/routing_service/mqtt/install_nanomq.sh,./core/routing_service/mqtt/install_nanomq.ps1 $TARGET_FOLDER
bash ../source_file_group.sh routing_services_aeron_install ./core/routing_service/aeron/install_aeronmd.ps1,./core/routing_service/aeron/install_aeronmd.sh,./core/routing_service/aeron/uninstall_aeronmd.sh $TARGET_FOLDER
bash ../source_file_group.sh routing_services_aeron_utils ./core/routing_service/aeron/update_sysctl.sh,./core/routing_service/aeron/aeron_1_26.ps1 $TARGET_FOLDER
bash ../source_file_group.sh routing_services_aeron_docs ./core/routing_service/aeron/README_windows.md,./core/routing_service/aeron/README_linux.md,./core/routing_service/aeron/Dockerfile.aeronmd_debian,./core/routing_service/aeron/Dockerfile.aeronmd_alpine $TARGET_FOLDER
bash ../source_file_group.sh widget_examples_simple_widgets ./core/examples/simple_widgets/args.rs,./core/examples/simple_widgets/main.rs,./core/examples/simple_widgets/actor/data_consumer.rs,./core/examples/simple_widgets/actor/data_approval.rs,./core/examples/simple_widgets/actor/data_feedback.rs,./core/examples/simple_widgets/actor/data_generator.rs $TARGET_FOLDER
bash ../source_file_group.sh widget_examples_large_scale ./core/examples/large_scale/args.rs,./core/examples/large_scale/main.rs,./core/examples/large_scale/actor/data_process.rs,./core/examples/large_scale/actor/data_user.rs,./core/examples/large_scale/actor/data_generator.rs,./core/examples/large_scale/actor/data_router.rs $TARGET_FOLDER
bash ../source_file_group.sh performance_examples_high_performance ./core/examples/high_performance/args.rs,./core/examples/high_performance/main.rs,./core/examples/high_performance/actor/final_consumer.rs,./core/examples/high_performance/actor/tick_consumer.rs,./core/examples/high_performance/actor/tick_generator.rs,./core/examples/high_performance/actor/tick_relay.rs $TARGET_FOLDER
bash ../source_file_group.sh performance_examples_high_durability ./core/examples/high_durability/args.rs,./core/examples/high_durability/main.rs,./core/examples/high_durability/actor/final_consumer.rs,./core/examples/high_durability/actor/tick_consumer.rs,./core/examples/high_durability/actor/tick_generator.rs,./core/examples/high_durability/actor/tick_relay.rs $TARGET_FOLDER
bash ../source_file_group.sh aeron_and_fizz_buzz_examples_simple_aeron_examples ./core/examples/simple_aeron_publisher/main.rs,./core/examples/simple_aeron_publisher/actor/publisher.rs,./core/examples/simple_aeron_subscriber/main.rs,./core/examples/simple_aeron_subscriber/actor/subscriber.rs $TARGET_FOLDER
bash ../source_file_group.sh aeron_and_fizz_buzz_examples_fizz_buzz ./core/examples/fizz_buzz/args.rs,./core/examples/fizz_buzz/main.rs,./core/examples/fizz_buzz/actor/fizz_buzz_processor.rs,./core/examples/fizz_buzz/actor/error_logger.rs,./core/examples/fizz_buzz/actor/timer_actor.rs,./core/examples/fizz_buzz/actor/console_printer.rs,./core/examples/fizz_buzz/actor/div_by_5_producer.rs,./core/examples/fizz_buzz/actor/div_by_3_producer.rs $TARGET_FOLDER
