name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

# TODO: https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
# TODO: https://github.com/actions/partner-runner-images/issues/26
# TODO: we need the most common permutations of features tested and covered

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Clean
      run: cargo clean
    - name: Build
      run: RUST_BACKTRACE=1 cargo build --verbose --no-default-features --features "proactor_nuclei,prometheus_metrics"
    - name: Run tests
      run: RUST_BACKTRACE=1 cargo test --verbose --no-default-features --features "proactor_nuclei,prometheus_metrics"
