name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Clean
      run: cargo clean
    - name: Build
      run: RUST_BACKTRACE=1 cargo build --verbose --no-default-features --features "proactor_nuclei,prometheus_metrics"
    - name: Run tests
      run: RUST_LOG=debug RUST_BACKTRACE=full cargo test --verbose --workspace --test --no-default-features --features "exec_async_std,prometheus_metrics" -- --show-output
