name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Clean
      run: cargo clean
    - name: Build
      run: cargo build --verbose --no-default-features --features "proactor_nuclei,prometheus_metrics"
    - name: Run tests
      run: cargo test --verbose --no-default-features --features "proactor_nuclei,prometheus_metrics" -- --cfg github_action
